version: '3'
services:
  web:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    env_file:
      - .env
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"